"""empty message

Revision ID: 08ebd09b0b86
Revises: 16e327f095b1
Create Date: 2022-08-26 12:06:26.414823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ebd09b0b86'
down_revision = '16e327f095b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'repUserId')
    op.add_column('user', sa.Column('joinGroup', sa.Integer(), nullable=True))
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['nickname'])
    op.create_foreign_key(None, 'user', 'group', ['joinGroup'], ['groupID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('user', 'joinGroup')
    op.add_column('group', sa.Column('repUserId', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
