"""empty message

Revision ID: 16e327f095b1
Revises: 07ccec49bae8
Create Date: 2022-08-26 12:05:35.256162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e327f095b1'
down_revision = '07ccec49bae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'group', 'user', ['repUserId'], ['id'])
    op.add_column('user', sa.Column('joinGroup', sa.Integer(), nullable=True))
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['nickname'])
    op.create_foreign_key(None, 'user', 'group', ['joinGroup'], ['groupID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('user', 'joinGroup')
    op.drop_constraint(None, 'group', type_='foreignkey')
    # ### end Alembic commands ###
