"""empty message

Revision ID: 18a6967b8596
Revises: c960e1d34e77
Create Date: 2022-08-30 16:02:14.597704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a6967b8596'
down_revision = 'c960e1d34e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ORDER_LIST', sa.Column('userID', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'ORDER_LIST', type_='foreignkey')
    op.create_foreign_key(None, 'ORDER_LIST', 'USER', ['userID'], ['id'], ondelete='CASCADE')
    op.drop_column('ORDER_LIST', 'ordered_userID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ORDER_LIST', sa.Column('ordered_userID', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'ORDER_LIST', type_='foreignkey')
    op.create_foreign_key(None, 'ORDER_LIST', 'USER', ['ordered_userID'], ['id'], ondelete='CASCADE')
    op.drop_column('ORDER_LIST', 'userID')
    # ### end Alembic commands ###
