"""empty message

Revision ID: 1c6b424cdcfc
Revises: 606071fe475f
Create Date: 2022-09-02 18:09:58.047804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c6b424cdcfc'
down_revision = '606071fe475f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'USER', type_='foreignkey')
    op.create_foreign_key(None, 'USER', 'GROUP', ['joinGroup'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'USER', type_='foreignkey')
    op.create_foreign_key(None, 'USER', 'GROUP', ['joinGroup'], ['id'])
    # ### end Alembic commands ###
