"""empty message

Revision ID: 24a72190ec8e
Revises: 321522255b6f
Create Date: 2022-08-27 15:11:45.253670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a72190ec8e'
down_revision = '321522255b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'USER', type_='foreignkey')
    op.create_foreign_key(None, 'USER', 'ORDER_GROUP', ['joinGroup'], ['groupID'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'USER', type_='foreignkey')
    op.create_foreign_key(None, 'USER', 'ORDER_GROUP', ['joinGroup'], ['groupID'])
    # ### end Alembic commands ###
