"""empty message

Revision ID: 34facea4eb6a
Revises: eae5fccd5fbd
Create Date: 2022-08-20 17:30:17.306304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34facea4eb6a'
down_revision = 'eae5fccd5fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('time', sa.DateTime(), nullable=True))
    op.add_column('group', sa.Column('delivery_cost', sa.Integer(), nullable=True))
    op.add_column('group', sa.Column('account_number', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('joinGroup', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'group', ['joinGroup'], ['groupID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'joinGroup')
    op.drop_column('group', 'account_number')
    op.drop_column('group', 'delivery_cost')
    op.drop_column('group', 'time')
    # ### end Alembic commands ###
