"""empty message

Revision ID: 793b387188a9
Revises: a8c048a6b081
Create Date: 2022-08-27 20:02:46.095525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793b387188a9'
down_revision = 'a8c048a6b081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ORDER_GROUP', type_='foreignkey')
    op.create_foreign_key(None, 'ORDER_GROUP', 'USER', ['repUserId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ORDER_GROUP', type_='foreignkey')
    op.create_foreign_key(None, 'ORDER_GROUP', 'USER', ['repUserId'], ['id'])
    # ### end Alembic commands ###
