"""empty message

Revision ID: 7c2ad95952b1
Revises: aad3853b468d
Create Date: 2022-09-01 23:56:57.890355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c2ad95952b1'
down_revision = 'aad3853b468d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'GROUP', type_='foreignkey')
    op.create_foreign_key(None, 'GROUP', 'USER', ['repUserId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'ORDER', type_='foreignkey')
    op.drop_constraint(None, 'ORDER', type_='foreignkey')
    op.create_foreign_key(None, 'ORDER', 'GROUP', ['groupID'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ORDER', 'USER', ['userID'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ORDER', type_='foreignkey')
    op.drop_constraint(None, 'ORDER', type_='foreignkey')
    op.create_foreign_key(None, 'ORDER', 'GROUP', ['groupID'], ['id'])
    op.create_foreign_key(None, 'ORDER', 'USER', ['userID'], ['id'])
    op.drop_constraint(None, 'GROUP', type_='foreignkey')
    op.create_foreign_key(None, 'GROUP', 'USER', ['repUserId'], ['id'])
    # ### end Alembic commands ###
