"""empty message

Revision ID: 8a3042874633
Revises: 24a72190ec8e
Create Date: 2022-08-27 15:12:03.778356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3042874633'
down_revision = '24a72190ec8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'USER', type_='foreignkey')
    op.create_foreign_key(None, 'USER', 'ORDER_GROUP', ['joinGroup'], ['groupID'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'USER', type_='foreignkey')
    op.create_foreign_key(None, 'USER', 'ORDER_GROUP', ['joinGroup'], ['groupID'])
    # ### end Alembic commands ###
