"""empty message

Revision ID: 8a9f131ce2dd
Revises: 7ab05a7df298
Create Date: 2022-09-01 11:41:38.636502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9f131ce2dd'
down_revision = '7ab05a7df298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ORDER_GROUP', type_='foreignkey')
    op.create_foreign_key(None, 'ORDER_GROUP', 'USER', ['repUserId'], ['id'])
    op.drop_constraint(None, 'ORDER_LIST', type_='foreignkey')
    op.drop_constraint(None, 'ORDER_LIST', type_='foreignkey')
    op.create_foreign_key(None, 'ORDER_LIST', 'USER', ['userID'], ['id'])
    op.create_foreign_key(None, 'ORDER_LIST', 'ORDER_GROUP', ['groupID'], ['groupID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ORDER_LIST', type_='foreignkey')
    op.drop_constraint(None, 'ORDER_LIST', type_='foreignkey')
    op.create_foreign_key(None, 'ORDER_LIST', 'USER', ['userID'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ORDER_LIST', 'ORDER_GROUP', ['groupID'], ['groupID'], ondelete='CASCADE')
    op.drop_constraint(None, 'ORDER_GROUP', type_='foreignkey')
    op.create_foreign_key(None, 'ORDER_GROUP', 'USER', ['repUserId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
