"""empty message

Revision ID: 97a61c50ee83
Revises: de88471714ad
Create Date: 2022-09-01 11:44:30.220462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97a61c50ee83'
down_revision = 'de88471714ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ORDER_GROUP',
    sa.Column('groupID', sa.Integer(), nullable=False),
    sa.Column('repUserId', sa.Integer(), nullable=True),
    sa.Column('store', sa.String(length=50), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('delivery_cost', sa.Integer(), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['repUserId'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('groupID')
    )
    op.create_table('USER',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('joinGroup', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['joinGroup'], ['ORDER_GROUP.groupID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('ORDER_LIST',
    sa.Column('orderID', sa.Integer(), nullable=False),
    sa.Column('groupID', sa.Integer(), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('menu', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('option', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['groupID'], ['ORDER_GROUP.groupID'], ),
    sa.ForeignKeyConstraint(['userID'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('orderID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ORDER_LIST')
    op.drop_table('USER')
    op.drop_table('ORDER_GROUP')
    # ### end Alembic commands ###
