"""empty message

Revision ID: 9b75d505bb37
Revises: 43d93bdc9aff
Create Date: 2022-08-20 17:40:30.694233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b75d505bb37'
down_revision = '43d93bdc9aff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('repUser', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'group', 'user', ['repUser'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'repUser')
    # ### end Alembic commands ###
