"""empty message

Revision ID: a7d6c9707d7e
Revises: ba28d8cdf920
Create Date: 2022-08-26 16:31:24.848772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d6c9707d7e'
down_revision = 'ba28d8cdf920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ORDER_GROUP',
    sa.Column('groupID', sa.Integer(), nullable=False),
    sa.Column('store', sa.String(length=50), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('delivery_cost', sa.Integer(), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('repUserId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repUserId'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('groupID')
    )
    op.create_table('USER',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('joinGroup', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['joinGroup'], ['ORDER_GROUP.groupID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('USER')
    op.drop_table('ORDER_GROUP')
    # ### end Alembic commands ###
