"""empty message

Revision ID: ba28d8cdf920
Revises: 926df127dd03
Create Date: 2022-08-26 16:29:39.930921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba28d8cdf920'
down_revision = '926df127dd03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ORDER_GROUP', sa.Column('repUserId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ORDER_GROUP', 'USER', ['repUserId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ORDER_GROUP', type_='foreignkey')
    op.drop_column('ORDER_GROUP', 'repUserId')
    # ### end Alembic commands ###
