"""empty message

Revision ID: c960e1d34e77
Revises: 7e81165dd948
Create Date: 2022-08-28 21:50:39.043754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c960e1d34e77'
down_revision = '7e81165dd948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ORDER_LIST',
    sa.Column('orderID', sa.Integer(), nullable=False),
    sa.Column('groupID', sa.Integer(), nullable=True),
    sa.Column('ordered_userID', sa.Integer(), nullable=True),
    sa.Column('menu', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('option', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['groupID'], ['ORDER_GROUP.groupID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ordered_userID'], ['USER.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('orderID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ORDER_LIST')
    # ### end Alembic commands ###
