"""empty message

Revision ID: d4b412611d5a
Revises: 97a61c50ee83
Create Date: 2022-09-01 21:00:05.915803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b412611d5a'
down_revision = '97a61c50ee83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GROUP',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repUserId', sa.Integer(), nullable=True),
    sa.Column('store', sa.String(length=50), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('delivery_cost', sa.Integer(), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['repUserId'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ORDER',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupID', sa.Integer(), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('menu', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('option', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['groupID'], ['GROUP.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ORDER_GROUP')
    op.drop_table('ORDER_LIST')
    op.drop_constraint(None, 'USER', type_='foreignkey')
    op.create_foreign_key(None, 'USER', 'GROUP', ['joinGroup'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'USER', type_='foreignkey')
    op.create_foreign_key(None, 'USER', 'ORDER_GROUP', ['joinGroup'], ['groupID'])
    op.create_table('ORDER_LIST',
    sa.Column('orderID', sa.INTEGER(), nullable=False),
    sa.Column('groupID', sa.INTEGER(), nullable=True),
    sa.Column('userID', sa.INTEGER(), nullable=True),
    sa.Column('menu', sa.VARCHAR(length=50), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('option', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['groupID'], ['ORDER_GROUP.groupID'], ),
    sa.ForeignKeyConstraint(['userID'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('orderID')
    )
    op.create_table('ORDER_GROUP',
    sa.Column('groupID', sa.INTEGER(), nullable=False),
    sa.Column('repUserId', sa.INTEGER(), nullable=True),
    sa.Column('store', sa.VARCHAR(length=50), nullable=True),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.Column('delivery_cost', sa.INTEGER(), nullable=True),
    sa.Column('account_number', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['repUserId'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('groupID')
    )
    op.drop_table('ORDER')
    op.drop_table('GROUP')
    # ### end Alembic commands ###
