"""empty message

Revision ID: dfadeb4be043
Revises: d6561af946b9
Create Date: 2022-08-19 15:18:53.648566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfadeb4be043'
down_revision = 'd6561af946b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('user', 'nickname',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['nickname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'nickname',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('user', 'id')
    # ### end Alembic commands ###
