"""empty message

Revision ID: e265d99e5a8e
Revises: 08ebd09b0b86
Create Date: 2022-08-26 12:07:54.281087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e265d99e5a8e'
down_revision = '08ebd09b0b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('groupID', sa.Integer(), nullable=False),
    sa.Column('store', sa.String(length=50), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('delivery_cost', sa.Integer(), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('groupID')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('joinGroup', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['joinGroup'], ['group.groupID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('group')
    # ### end Alembic commands ###
