"""empty message

Revision ID: e7cb04752226
Revises: 012bdcaafd2b
Create Date: 2022-08-20 17:46:25.589934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7cb04752226'
down_revision = '012bdcaafd2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('repUserId', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.create_foreign_key(None, 'group', 'user', ['repUserId'], ['id'])
    op.drop_column('group', 'repUser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('repUser', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.create_foreign_key(None, 'group', 'user', ['repUser'], ['id'])
    op.drop_column('group', 'repUserId')
    # ### end Alembic commands ###
